### ISSUE TITLE
drop GEM_HOME env

### ISSUE THREAD

**Issue by y-ken** [embulk/embulk-input-command#6]
To execute cruby from this plugin, `GEM_HOME` env are blocked to load gems in cruby.
In other word, This plugin keeps jruby GEM_HOME but it is unnecessary in usual case.

`GEM_HOME=/Users/y-ken/.embulk/jruby/2.3.0`

### how to find GEM_HOME env

```bash:how_to_repeat
$ cat test.yml
in:
  type: command
  command: env
  parser:
   type: none

$ embulk preview -G test.yml
```

![_2017_03_11_9_46](https://cloud.githubusercontent.com/assets/1734549/23818595/ed17eb2c-063f-11e7-8b50-e300732a2fec.png)

## workarounds

For now, I have override GEM_HOME env to execute cruby

```
in:
  type: command
  command: GEM_HOME=~/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0 ruby collect_foo_bar.rb
  parser:
   type: jsonl
   columns:
    ...snip...
```

cf. http://blog.shibayu36.org/entry/2014/01/15/230015

**Comment by hiroyuki-sato** [comment]
I think the following option is useful.


```
in:
  type: command
  restore_gem_env: true
  command: 
```  

However, this option needs to modify the Embulk itself for store original `GEM_HOME` and `GEM_PATH`. 
That because the Embulk remove the environment variables(`GEM_HOME` and `GEM_PATH`).

**Comment by y-ken** [comment]
It sounds nice to have restore env option!
Restore all of env is better to have selective option and default true.

```
in:
  type: command
  restore_env: true
  command: 
```

**Comment by dmikurube** [comment]
@y-ken Thanks for filing the issue. I'm a bit concerned that it may have a big impact to change the Embulk core side.

@hiroyuki-sato Do you think that adding an `env` (or some other name) configuration in embulk-input-command does work?

I mean :
```
in:
  type: command
  env:
    GEM_HOME: <brabrabra>
  command: <brabrabra>
```

**Comment by hiroyuki-sato** [comment]
@dmikurube Thank you for the comment.

IMO, It doesn't need `env` option **now**.
 

Here is the reason. 

* First reason 
  * The current workaround work correctly without `env` parameter. 
  * It is mean that the following configuration may work almost the same. 

```yaml
in:
  type: command
  command: GEM_HOME=~/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0 ruby collect_foo_bar.rb
  parser:
   type: jsonl
   columns:
    ...snip...
```

* Second reason
  * In my environment `GEM_HOME` and `GEM_PATH` does not define before executing `embulk`.
  * So **Restore** mean that **unset** those variable instead of overriding it. 


Totally, this issue has a workaround. So It's not a critical issue. 

The Embulk team are planning about next stage. 
I recommend the team to refactor(redesign/consider carefully) this behavior.
